/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ScaleBadgeComponent {
        "color": 'magenta' | 'white' | 'black' | string;
        "rotation": number;
        "size": 'big' | 'small';
    }
}
declare global {
    interface HTMLScaleBadgeComponentElement extends Components.ScaleBadgeComponent, HTMLStencilElement {
    }
    var HTMLScaleBadgeComponentElement: {
        prototype: HTMLScaleBadgeComponentElement;
        new (): HTMLScaleBadgeComponentElement;
    };
    interface HTMLElementTagNameMap {
        "scale-badge-component": HTMLScaleBadgeComponentElement;
    }
}
declare namespace LocalJSX {
    interface ScaleBadgeComponent {
        "color"?: 'magenta' | 'white' | 'black' | string;
        "rotation"?: number;
        "size"?: 'big' | 'small';
    }
    interface IntrinsicElements {
        "scale-badge-component": ScaleBadgeComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "scale-badge-component": LocalJSX.ScaleBadgeComponent & JSXBase.HTMLAttributes<HTMLScaleBadgeComponentElement>;
        }
    }
}
