/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ScaleBadge {
    }
}
declare global {
    interface HTMLScaleBadgeElement extends Components.ScaleBadge, HTMLStencilElement {
    }
    var HTMLScaleBadgeElement: {
        prototype: HTMLScaleBadgeElement;
        new (): HTMLScaleBadgeElement;
    };
    interface HTMLElementTagNameMap {
        "scale-badge": HTMLScaleBadgeElement;
    }
}
declare namespace LocalJSX {
    interface ScaleBadge {
    }
    interface IntrinsicElements {
        "scale-badge": ScaleBadge;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "scale-badge": LocalJSX.ScaleBadge & JSXBase.HTMLAttributes<HTMLScaleBadgeElement>;
        }
    }
}
